### ISSUE TITLE
Rename the repo

### ISSUE THREAD

**Issue by kelly-sovacool** [UMCarpentries/intro-curriculum-r#134]
"curriculum" is too vague. In the future we might also like to make a curriculum teaching Python in place of R.

**Comment by kelly-sovacool** [comment]
Ideas: 
- `r-intro-curriculum`. (doesn’t acknowledge other skills though)
- `rrr-curriculum`. rrr = reproducible research with R. hard to remember how many R’s to use though…
- `intro-curriculum-r`. @zenalapp

**Comment by pschloss** [comment]
What is the consensus for the name?

**Comment by zenalapp** [comment]
We currently don't have a consensus. I think of the 3 above my vote is `intro-curriculum-r`, but definitely open to other ideas too!

**Comment by kelly-sovacool** [comment]
I wish there were a way to convey what makes our curriculum unique -- lessons are interdependent and integrate r/unix/git skills together, and focuses on reproducible research workflows

**Comment by kelly-sovacool** [comment]
Maybe we should just go with `intro-curriculum-r` and not overthink it.

**Comment by kelly-sovacool** [comment]
If we think of something better, we can rename it again in the future.
